In [ ]:
import pandas as pd

In [ ]:
df2021 = pd.read_csv("2021.csv")
df2022 = pd.read_csv('2022.csv')
df2023 = pd.read_csv('2023.csv')
df2024 = pd.read_csv('2024.csv')
df2025 = pd.read_csv('2025.csv')

In [23]:
df = pd.concat(
    [df2021, df2022, df2023, df2024, df2025],
    ignore_index=True
)

print("Total rows and columns:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

df.head()

Total rows and columns: (23822963, 11)

Column names:
['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade', 'Arrival_Date', 'Min_Price', 'Max_Price', 'Modal_Price', 'Commodity_Code']

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price,Commodity_Code
0,Andhra Pradesh,Chittor,Chittoor,Gur (Jaggery),NO 1,FAQ,2021-01-01,4000.0,4500.0,4000.0,74
1,Andhra Pradesh,Chittor,Mulakalacheruvu,Tomato,Local,FAQ,2021-01-01,550.0,1150.0,850.0,78
2,Andhra Pradesh,Chittor,Vayalapadu,Tomato,Local,FAQ,2021-01-01,360.0,1200.0,800.0,78
3,Andhra Pradesh,Guntur,Tenali,Black Gram (Urd Beans)(Whole),Black Gram (Whole),FAQ,2021-01-01,6300.0,7000.0,6600.0,8
4,Andhra Pradesh,Guntur,Tenali,Lemon,Lemon,FAQ,2021-01-01,1500.0,2200.0,1800.0,310

In [24]:
haryana_df = df[df["State"].astype(str).str.strip().str.lower() == "haryana"].copy()

print("Haryana rows:", haryana_df.shape)

print("\nHaryana date range:")
print("From:", haryana_df["Arrival_Date"].min())
print("To:", haryana_df["Arrival_Date"].max())

print("\nTotal unique commodities:", haryana_df["Commodity"].nunique())

print("\nCommodities available in Haryana:")
print(sorted(haryana_df["Commodity"].dropna().unique()))

Haryana rows: (964476, 11)

Haryana date range:
From: 2021-01-01
To: 2025-10-20

Total unique commodities: 118

Commodities available in Haryana:
['Ajwan', 'Almond (Badam)', 'Alsandikai', 'Amla (Nelli Kai)', 'Apple', 'Apricot (Jardalu/Khumani)', 'Ashgourd', 'Bajra (Pearl Millet/Cumbu)', 'Banana', 'Banana - Green', 'Barley (Jau)', 'Beetroot', 'Bengal Gram (Gram)(Whole)', 'Bengal Gram Dal (Chana Dal)', 'Ber (Zizyphus/Borehannu)', 'Bhindi (Ladies Finger)', 'Binoula', 'Bitter gourd', 'Black Gram (Urd Beans)(Whole)', 'Bottle gourd', 'Brinjal', 'Cabbage', 'Capsicum', 'Carrot', 'Cauliflower', 'Chapparad Avare', 'Chennangi Dal', 'Cherry', 'Chikoos (Sapota)', 'Chili Red', 'Cluster beans', 'Colacasia', 'Coriander (Leaves)', 'Cotton', 'Cotton Seed', 'Cucumbar (Kheera)', 'Drumstick', 'Dry Fodder', 'Duster Beans', 'Elephant Yam (Suran)', 'French Beans (Frasbean)', 'Galgal (Lemon)', 'Garlic', 'Ginger (Dry)', 'Ginger (Green)', 'Gram Raw (Chholia)', 'Grapes', 'Green Chilli', 'Green Fodder', 'Green Gram (Moong)(Whole)', 'Green Gram Dal (Moong Dal)', 'Green Peas', 'Groundnut', 'Guar', 'Guar Seed (Cluster Beans Seed)', 'Guava', 'Indian Beans (Seam)', 'Indian Colza (Sarson)', 'Jack Fruit', 'Jamun (Narale Hannu)', 'Jowar (Sorghum)', 'Karbuja (Musk Melon)', 'Kinnow', 'Leafy Vegetable', 'Lemon', 'Lime', 'Litchi', 'Little gourd (Kundru)', 'Long Melon (Kakri)', 'Lukad', 'Maize', 'Mango', 'Mango (Raw-Ripe)', 'Mashrooms', 'Methi (Leaves)', 'Methi Seeds', 'Mint (Pudina)', 'Mousambi (Sweet Lime)', 'Mustard', 'Onion', 'Onion Green', 'Orange', 'Paddy (Dhan)(Basmati)', 'Paddy (Dhan)(Common)', 'Papaya', 'Papaya (Raw)', 'Peach', 'Pear (Marasebu)', 'Peas (Dry)', 'Peas Wet', 'Peas cod', 'Pineapple', 'Plum', 'Pointed gourd (Parval)', 'Pomegranate', 'Potato', 'Pumpkin', 'Raddish', 'Ridgeguard (Tori)', 'Round gourd', 'Safflower', 'Season Leaves', 'Seetapal', 'Spinach', 'Sponge gourd', 'Squash (Chappal Kadoo)', 'Sunflower', 'Sweet Potato', 'Tamarind Fruit', 'Tender Coconut', 'Tinda', 'Tomato', 'Toria', 'Turnip', 'Water Melon', 'Wheat', 'White Pumpkin', 'Yam (Ratalu)']

In [25]:
keywords = ["wheat", "paddy", "rice", "bajra", "mustard", "cotton"]

for word in keywords:
    matches = haryana_df[
        haryana_df["Commodity"]
        .str.contains(word, case=False, na=False)
    ]["Commodity"].unique()

    print(f"\n{word.upper()}:")
    print(matches)

WHEAT:
['Wheat']

PADDY:
['Paddy (Dhan)(Basmati)' 'Paddy (Dhan)(Common)']

RICE:
[]

BAJRA:
['Bajra (Pearl Millet/Cumbu)']

MUSTARD:
['Mustard']

COTTON:
['Cotton' 'Cotton Seed']

In [26]:
selected_commodities = [
    "Wheat",
    "Paddy (Dhan)(Basmati)",
    "Paddy (Dhan)(Common)",
    "Bajra (Pearl Millet/Cumbu)",
    "Mustard",
    "Cotton"
]

crop_df = haryana_df[
    haryana_df["Commodity"].isin(selected_commodities)
].copy()

print("Total selected rows:", crop_df.shape)

print("\nRows per commodity:")
print(crop_df["Commodity"].value_counts())

Total selected rows: (38832, 11)

Rows per commodity:
Commodity
Paddy (Dhan)(Basmati)         9526
Mustard                       8403
Cotton                        8298
Wheat                         5222
Paddy (Dhan)(Common)          4692
Bajra (Pearl Millet/Cumbu)    2691
Name: count, dtype: int64

In [27]:
crop_df["Arrival_Date"] = pd.to_datetime(
    crop_df["Arrival_Date"],
    errors="coerce"
)

crop_df["Year"] = crop_df["Arrival_Date"].dt.year

year_crop_count = pd.crosstab(
    crop_df["Year"],
    crop_df["Commodity"]
)

print(year_crop_count)

Commodity  Bajra (Pearl Millet/Cumbu)  Cotton  Mustard  Paddy (Dhan)(Basmati)  \
Year
2021                               53      92       97                    532
2022                              397    1610     1906                   1722
2023                              773    2405     2408                   2305
2024                              727    2323     1748                   3087
2025                              741    1868     2244                   1880

Commodity  Paddy (Dhan)(Common)  Wheat
Year
2021                        283    197
2022                        591    938
2023                       1433   1193
2024                       1405   1209
2025                        980   1685

In [ ]:
print("DATA TYPES:")
print(crop_df.dtypes)

print("\nMISSING VALUES:")
print(crop_df.isnull().sum())

print("\nDUPLICATE ROWS:")
print(crop_df.duplicated().sum())

print("\nDATASET SIZE:")
print(crop_df.shape)

In [28]:
print("Duplicate rows:", crop_df.duplicated().sum())

print("\nZero or negative prices:")
print("Min Price:", (crop_df["Min_Price"] <= 0).sum())
print("Max Price:", (crop_df["Max_Price"] <= 0).sum())
print("Modal Price:", (crop_df["Modal_Price"] <= 0).sum())

print("\nInvalid price relationships:")

print(
    "Min Price > Max Price:",
    (crop_df["Min_Price"] > crop_df["Max_Price"]).sum()
)

print(
    "Modal Price < Min Price:",
    (crop_df["Modal_Price"] < crop_df["Min_Price"]).sum()
)

print(
    "Modal Price > Max Price:",
    (crop_df["Modal_Price"] > crop_df["Max_Price"]).sum()
)

Duplicate rows: 0

Zero or negative prices:
Min Price: 1
Max Price: 11
Modal Price: 0

Invalid price relationships:
Min Price > Max Price: 10
Modal Price < Min Price: 0
Modal Price > Max Price: 11

In [29]:
problem_rows = crop_df[
    (crop_df["Min_Price"] <= 0) |
    (crop_df["Max_Price"] <= 0) |
    (crop_df["Modal_Price"] <= 0) |
    (crop_df["Min_Price"] > crop_df["Max_Price"]) |
    (crop_df["Modal_Price"] < crop_df["Min_Price"]) |
    (crop_df["Modal_Price"] > crop_df["Max_Price"])
]

print("Total problematic rows:", len(problem_rows))

problem_rows[
    [
        "Arrival_Date",
        "District",
        "Market",
        "Commodity",
        "Variety",
        "Min_Price",
        "Max_Price",
        "Modal_Price"
    ]
]

Total problematic rows: 11

,Arrival_Date,District,Market,Commodity,Variety,Min_Price,Max_Price,Modal_Price
5157270,2022-04-17,Kaithal,Pai (Rajaund),Wheat,Other,2015.0,0.0,2015.0
5180531,2022-04-19,Kaithal,Pai (Rajaund),Wheat,Other,2015.0,0.0,2015.0
9577147,2023-04-15,Ambala,Naneola,Wheat,Other,2125.0,0.0,2125.0
11308569,2023-09-02,Fatehabad,Tohana,Cotton,American,6400.0,0.0,6605.0
11430308,2023-09-13,Mewat,Hathin,Bajra (Pearl Millet/Cumbu),Other,1700.0,0.0,1900.0
12205265,2023-11-18,Kurukshetra,Ladwa,Paddy (Dhan)(Common),Other,2500.0,0.0,4705.0
12547286,2023-12-16,Fatehabad,Bhattu Kalan,Mustard,Other,4971.0,0.0,4971.0
19288761,2025-02-22,Mewat,Hathin,Bajra (Pearl Millet/Cumbu),Other,2200.0,0.0,2200.0
20218647,2025-04-10,Bhiwani,Jui,Mustard,Other,5950.0,0.0,5950.0
23387049,2025-09-24,Ambala,Naneola,Paddy (Dhan)(Common),Paddy,2389.0,0.0,2389.0
23615470,2025-10-08,Mewat,Hathin,Bajra (Pearl Millet/Cumbu),Other,0.0,0.0,1900.0

In [31]:
clean_df = crop_df[
    (crop_df["Min_Price"] > 0) &
    (crop_df["Max_Price"] > 0) &
    (crop_df["Modal_Price"] > 0) &
    (crop_df["Min_Price"] <= crop_df["Modal_Price"]) &
    (crop_df["Modal_Price"] <= crop_df["Max_Price"])
].copy()

print("Before cleaning:", crop_df.shape)
print("After cleaning:", clean_df.shape)
print("Rows removed:", len(crop_df) - len(clean_df))

Before cleaning: (38832, 12)
After cleaning: (38821, 12)
Rows removed: 11

In [ ]:
clean_df.head()

In [ ]:
clean_df.to_csv("haryana_crop_prices_cleaned.csv", index=False)

In [ ]:
wheat_df = clean_df[
    clean_df["Commodity"] == "Wheat"
].copy()

bajra_df = clean_df[
    clean_df["Commodity"] == "Bajra (Pearl Millet/Cumbu)"
].copy()

mustard_df = clean_df[
    clean_df["Commodity"] == "Mustard"
].copy()

cotton_df = clean_df[
    clean_df["Commodity"] == "Cotton"
].copy()

paddy_basmati_df = clean_df[
    clean_df["Commodity"] == "Paddy (Dhan)(Basmati)"
].copy()

paddy_common_df = clean_df[
    clean_df["Commodity"] == "Paddy (Dhan)(Common)"
].copy()

In [ ]:
print(wheat_df.head())
print(bajra_df.head())
print(mustard_df.head())
print(cotton_df.head())
print(paddy_basmati_df.head())
print(paddy_common_df.head())

In [ ]:
wheat_df.shape

In [ ]:
wheat_df.to_csv("wheat_cleaned.csv", index=False)
bajra_df.to_csv("bajra_cleaned.csv", index=False)
mustard_df.to_csv("mustard_cleaned.csv", index=False)
cotton_df.to_csv("cotton_cleaned.csv", index=False)
paddy_basmati_df.to_csv("paddy_basmati_cleaned.csv", index=False)
paddy_common_df.to_csv("paddy_common_cleaned.csv", index=False)